-- Check all tables that might have CreatedOn column
SELECT 
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE c.COLUMN_NAME = 'CreatedOn' OR t.TABLE_NAME = 'Leads'
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

-- Check if there are multiple Leads tables or schemas
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Lead%'
ORDER BY TABLE_SCHEMA, TABLE_NAME;